import Head from 'next/head'
import Image from 'next/image'
// import Script from 'next/script'
// import Link from "next/link"
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
            .mySpan{
              color:red;
            }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/script.js' strategy='lazyOnload'></Script> */}

      

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan dummy'></span>Hunting Coder
        </h1>
        <div className={styles.imgWrap}>
          <Image src="/homeImg.jpg" alt="home coder" width={320} height={213} className={styles.myImg} />
        </div>

        <p className={styles.description}>
          A blog for coders by hunting coder
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022 ?</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, quos optio veritatis illum ducimus ut debitis?</p>
          </div>
        </div>
      </main>

     
    </div>
  )
}
